### ISSUE TITLE
Adding a game

### ISSUE THREAD

**Issue by mapmeld** [unixpickle/muniverse#1]
Hi - I'm trying to add a small HTML5 game to muniverse on my machine. As we discussed over email, I'll post info about the process and if everything works it can be present as documentation.

My initial branch is based on the game added in this commit: https://github.com/unixpickle/muniverse/commit/d5482964c23d3d21f3550850203ee9df003c9cca

Based on your instructions, I will either (a) change the muniverse Docker container, or (b) make a new Docker container based on this one, which downloads the game into the container as an additional step

Then with muniverse-agent:

```
In order to tell µniverse to use a custom Docker image, you should use the NewEnvContainer API. I just added a flag to muniverse-agent to let you do this: -image.
```

I'll try this in the next couple of days

**Comment by unixpickle** [comment]
My original complete response:

> When µniverse runs a game in Chrome, Chrome looks for that game inside the Docker container. By default, the Docker image it uses is from the internet and is packaged with all of the default games. If you want µniverse to run a game that is not in the default container, you will want to build your own Docker image and use that. One way to build an image is to follow the steps in https://github.com/unixpickle/muniverse/tree/master/container. The first time you follow the steps at that link, the build make take 10-20 minutes. Another, potentially faster way would be to create a new Docker image and use unixpickle/muniverse:0.56.0 as a base image, then to copy your game into /downloaded_games.
>
> In order to tell µniverse to use a custom Docker image, you should use the NewEnvContainer API. I just added a flag to muniverse-agent to let you do this: -image.
>
> At some point in the future, I may make it so that µniverse can load games from outside of the Docker container. It shouldn't be too hard with Docker volumes, but I want to be sure I do it in a nice, sustainable way.
>
> I do think the error message you saw wasn't very helpful. I will try to work out a better way to detect a 404 page.

If you are willing to wait a little while, I'm going to try adding the feature I mentioned to specify a custom `downloaded_games` directory without creating a new container. I don't actually think it will be that hard, and it will be helpful for development.

**Comment by unixpickle** [comment]
By the way, there is some basic documentation [here](https://github.com/unixpickle/muniverse/tree/master/games#adding-a-game) about adding a game.

**Comment by unixpickle** [comment]
I'm going to close this issue due to inactivity. Ping me if/when I should re-open it. At some point soon I'd like to create a better step-by-step guide for adding a game, but I want to wait until a stable release of µniverse.
