### ISSUE TITLE
Issue with doodle jump and docker container 0.111.1+

### ISSUE THREAD

**Issue by Grant-E-G** [unixpickle/muniverse#5]
Running doodle jump works with container version 0.111.0 but fails for higher version. I can see reward data from a3c, and I can produce recordings, but on higher versions, both are missing. If I supply a recording directory, then I get 8 subdirectories but with 0 images.

**Comment by unixpickle** [comment]
Just noticed this issue as well. The problem is that the new chrome enables webgl on a lot of games, and that breaks muniverse's canvas -> pixels optimization. I have a fix coming that will fix a lot of games, since it seems a large number of games were broken by the chrome upgrade.

**Comment by unixpickle** [comment]
Should be fixed in in 0b73bec009de16442c3155d2d387c147ed795da5 (container version 0.112.1). Let me know if it's not fixed for you.
